---
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write
 
jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/nboci"
        binary_name: "nboci"
        extra_files: LICENSE README.md
        md5sum: false
